[build]
  functions = "netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':(exclude)push-subscription.json' ':(exclude)history.json'"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[functions."push-send"]
  schedule = "0 7,19 * * *"
